// Package posture implements kbounce's per-bouncer posture surface.
//
// Shared between `kbounce posture` (CLI) + `kbounce_posture` (MCP)
// per [[cross-product-agent-parity]]. Lives in its own package so
// neither cli nor mcp pulls the other.
//
// Per [[ibounce-honest-positioning]]: the output is HONEST — if
// KUBECONFIG points at a kbounce-generated kubeconfig but kbounce
// isn't running, the snapshot reports MISCONFIGURED rather than
// silently claiming intercept.
//
// Per [[creates-never-mutates]]: read-only; the package never writes
// to disk, never mutates env, never starts goroutines.
package posture

import (
	"fmt"
	"net"
	"os"
	"strings"
	"time"

	"github.com/trsreagan3/kbouncer/internal/kbenv"
)

// SchemaVersion pins the shape of the JSON output. Bump on breaking
// changes per [[config-export-wire-divergence]] (string per the
// cross-product convention).
const SchemaVersion = "1.0"

// DefaultPort kbounce listens on. Mirrors the `--port` flag default
// in newRunCmd; kept here as an exported const so tests can pin the
// value without scraping the cobra command tree.
const DefaultPort = 8766

// KubeconfigMarker is stamped at the top of any kubeconfig kbounce
// generates (e.g. via `kbounce kubeconfig`). Matches the Python
// posture detector's KBOUNCE_KUBECONFIG_MARKER so an `iam-jit
// posture` run from outside the kbounce process sees the same
// signal a `kbounce posture` run from inside it sees.
const KubeconfigMarker = "# Generated by kbounce"

// EnvProfileVar is the env-var name used to select the active
// profile when --profile is not passed. Matches the cli package's
// envProfileVar.
const EnvProfileVar = "KBOUNCER_PROFILE"

// EnvModeVar is the env-var name that pins kbounce's operating mode
// for the posture snapshot. We don't try to read the LIVE mode of a
// running kbounce (would need a /healthz round-trip); env or
// "unknown" is the honest answer.
const EnvModeVar = "KBOUNCER_MODE"

// Block is the structured snapshot rendered as JSON. Field names +
// types match the per-bouncer block in the iam-roles posture
// schema so cross-product orchestrators can map kbounce's output
// straight into the unified view.
type Block struct {
	SchemaVersion      string `json:"schema_version"`
	Bouncer            string `json:"bouncer"`
	CapturedAt         string `json:"captured_at"`
	Running            bool   `json:"running"`
	Port               int    `json:"port"`
	DefaultPort        int    `json:"default_port"`
	Mode               string `json:"mode"`
	ActiveProfile      string `json:"active_profile"`
	EnvVarPointingHere string `json:"env_var_pointing_here,omitempty"`
	EnvVarSetElsewhere string `json:"env_var_set_elsewhere,omitempty"`
	Misconfig          string `json:"misconfig,omitempty"`
	KubeconfigPath     string `json:"kubeconfig_path,omitempty"`
}

// Capture builds the structured snapshot. No goroutines, no
// background IO — just env reads + a single loopback TCP probe.
// Always safe to call.
func Capture() Block {
	port := DefaultPort
	running := loopbackPortOpen(port, 250*time.Millisecond)
	block := Block{
		SchemaVersion: SchemaVersion,
		Bouncer:       "kbounce",
		CapturedAt:    time.Now().UTC().Format(time.RFC3339),
		Running:       running,
		Port:          port,
		DefaultPort:   DefaultPort,
		Mode:          envOrUnknown(EnvModeVar),
		ActiveProfile: envOrUnknown(EnvProfileVar),
	}
	kubecfg := strings.TrimSpace(os.Getenv("KUBECONFIG"))
	if kubecfg != "" {
		block.KubeconfigPath = kubecfg
		if kubeconfigIsKbounce(kubecfg) {
			block.EnvVarPointingHere = fmt.Sprintf(
				"KUBECONFIG=%s (kbounce-generated)", kubecfg,
			)
			if !running {
				block.Misconfig = fmt.Sprintf(
					"KUBECONFIG=%s points at a kbounce-generated kubeconfig "+
						"but kbounce isn't running on port %d",
					kubecfg, port,
				)
			}
		} else {
			block.EnvVarSetElsewhere = fmt.Sprintf(
				"KUBECONFIG=%s (not kbounce-generated)", kubecfg,
			)
		}
	}
	return block
}

// envOrUnknown resolves a kbounce env var (accepting both the
// KBOUNCER_ and KBOUNCE_ prefixes via kbenv) and returns "unknown"
// when neither is set.
func envOrUnknown(name string) string {
	v := strings.TrimSpace(kbenv.Get(name))
	if v == "" {
		return "unknown"
	}
	return v
}

func loopbackPortOpen(port int, timeout time.Duration) bool {
	if port <= 0 || port > 65535 {
		return false
	}
	conn, err := net.DialTimeout(
		"tcp", fmt.Sprintf("127.0.0.1:%d", port), timeout,
	)
	if err != nil {
		return false
	}
	_ = conn.Close()
	return true
}

func kubeconfigIsKbounce(path string) bool {
	if path == "" {
		return false
	}
	data, err := os.ReadFile(path) // nolint: gosec — operator path
	if err != nil {
		return false
	}
	head := string(data)
	if len(head) > 1024 {
		head = head[:1024]
	}
	return strings.Contains(head, KubeconfigMarker)
}
